### ISSUE TITLE
Getting curl error "-->: is unknown" after loading IP from ifconfig.io

### ISSUE THREAD

**Issue by chrgm** [FarrowStrange/hetzner-api-dyndns#14]
I get the following error when using the script. 

> Info: Record_Name: vpn : Zone_ID: ZONE_ID
Info: Record_Name: vpn : Zone_Name: ZONE_NAME
Info: Record_Name: vpn : Using IPv4 as record type A is not explicitly AAAA.
Info: Record_Name: vpn : Record_ID: RECORD_ID
Info: Record_Name: vpn : Current public IP Address: 123.456.789.0
DNS record "vpn" is no longer valid - updating record
curl: option -->: is unknown
curl: try 'curl --help' or 'curl --manual' for more information
Error: Record_Name: vpn : Unable to update record: "vpn"

When I checked the variables the script uses I figured out that `${cur_pub_addr}` contains the whole HTML code of ifconfig.io and not just a single IP address. 
This leads in line 144 to an always false statement as a single IP address never matches a whole HTML page. And when calling the PUT statement with curl from line 149 the error occurs with `${cur_pub_addr}` as parameter it failes.
Is there some HTML parsing necessary or is my curl strange when getting the `${cur_pub_addr}` ?

EDIT: I figured out that Cloudflare is the problem. When I call `curl -4 -s ifconfig.co` from my commandline I get the Cloudflare captcha page and the IP adress is hidden in the HTML page.

FIX options: 
-  choosing different public IP providers (e.g. ifconfig.io)
- parsing the HTML code (I think just too unnecessary (it is the public IP address cloudflare shows)
- provide an error message when Cloudflare captchas happend

**Comment by FarrowStrange** [comment]
Hey @chrgm,

unfortunately I could not reproduce your error so far. I tried the query from different locations and never got a captcha.

In the initial version of the script `ifconfig.io` was used, unfortunately there is no support for IPv6 here.
If you only use IPv4, I would suggest you to use `ifconfig.io` to determine the public ip address - as a short-term workaround.

I am always looking for new ways / providers to determine the public ip address and am open to suggestions. It would certainly be good to include a fallback provider to increase reliability.


I just saw that you have already opened a pull request to catch the error code - Thanks 🚀

**Comment by chrgm** [comment]
For me Cloudflare showed up almost every time I opened ifconfig.co in a new private window or with curl. I don't know what the rules for Cloudflare are. 
Best would be Hetzner implementing the IP lookup in their API.

**Comment by FarrowStrange** [comment]
Since [hetzner-api-dyndns-2101121553](https://github.com/FarrowStrange/hetzner-api-dyndns/pull/16) the public ip is determined via DNS. This offers a more reliable and highly available alternative. 

Due to the change there are no more captchas.
