### ISSUE TITLE
Script doesn't work

### ISSUE THREAD

**Issue by moesizlag** [FarrowStrange/hetzner-api-dyndns#18]
Sorry if this is a totally dumb callout as I'm not really familiar with bash scripting.
Downloaded v.1.1 of the script but even with calling it minimum parameters from the readme example it shows errors right away:
**./dyndns.sh -Z example.com -n dyn -T AAAA
jq: error (at <stdin>:1): Cannot iterate over null (null)
jq: error (at <stdin>:1): Cannot iterate over null (null)
Error: Record_Name: : Something went wrong. Could not find Zone ID.
Error: Record_Name: : Check your inputs of either -z <Zone ID> or -Z <Zone Name>.
Error: Record_Name: : Use -h to display help.**

**Comment by FarrowStrange** [comment]
Hey @moesizlag,
sorry for late response. Can you tell me how you pass the API token? Do you pass this as an environment variable, or do you have the API token stored directly in the script?

**There are several ways to pass the token:** 
1. If you call the script in a cronjob, you can specify the API token directly as an environment variable in the crontab.
```
HETZNER_AUTH_API_TOKEN='<your-hetzner-dns-api-token>'

*/5 * * * * /usr/bin/dyndns.sh -Z example.com -n dyn -T AAAA
```

2. If you want to call the script directly from the command line (e.g. if you want to test something), then you have to export the API token as Environment Variable, or write the token directly into the script, as described in the next point.
```
$ export HETZNER_AUTH_API_TOKEN='<your-hetzner-dns-api-token>'

$ ./dyndns.sh -Z example.com -n dyn -T AAAA
```

3. The last option is to store the API token directly in the script. The corresponding option can be found in line 6 of the script.
```
...
auth_api_token=${HETZNER_AUTH_API_TOKEN:-'<your-hetzner-dns-api-token>'}
...
```

**Comment by moesizlag** [comment]
Hi @FarrowStrange,

thx a lot and seems it was just a too long day for me and actually wrongly passed the ENV :-(
Works perfectly fine now and thx for providing that helpful script!

The section where you check for the API Token doesn't seem to catch the case where no Token has been provided via the ENV HETZNER_AUTH_API_TOKEN and Script, maybe a feature request to fix that ;)

**Comment by FarrowStrange** [comment]
Hi @moesizlag,

I am glad that I could help you. If you have any other problems or suggestions for improvement, just get in touch. 

You are absolutely right, in the script a variable () is set as a placeholder, which is normally overwritten by the environment variable. So if no token is passed, it uses this placeholder as token.  
```
auth_api_token=${HETZNER_AUTH_API_TOKEN:-'<your-hetzner-dns-api-token>'}
```

I will create a fix to filter out this case and output a message if no token was passed or authentication was not successful.  


Thanks for your help 😄

**Comment by MrTiptop** [comment]
Hello, i am getting the same issue here.. what am i missing ?
# ./dyndns.sh -Z example.com -n dyn -T AAAA
Error: Record_Name: dyn : Something went wrong. Could not find Zone ID.
Error: Record_Name: dyn : Check your inputs of either -z <Zone ID> or -Z <Zone Name>.
Error: Record_Name: dyn : Use -h to display help.

**Comment by FarrowStrange** [comment]
Hey @MrTiptop,

can you tell me how you call the script? Additionally it would be helpful to know how you pass the API token. Du you pass it as an environment variable, or do you have the API token stored directly in the script?

**Comment by MrTiptop** [comment]
if i download your script and run it from Terminal
```
# export export HETZNER_AUTH_API_TOKEN='<xxxxxxxbbbbbbbbb>'
# ./dyndns.sh -Z example.com -n dyn -T AAAA
Error: Record_Name: dyn : Something went wrong. Could not find Zone ID.
Error: Record_Name: dyn : Check your inputs of either -z or -Z .
Error: Record_Name: dyn : Use -h to display help.
```

also i have tried this with same results
```
# export export HETZNER_AUTH_API_TOKEN='xxxxxxxbbbbbbbbb'
# ./dyndns.sh -Z example.com -n dyn -T AAAA
Error: Record_Name: dyn : Something went wrong. Could not find Zone ID.
Error: Record_Name: dyn : Check your inputs of either -z or -Z .
Error: Record_Name: dyn : Use -h to display help.
```

**Comment by FarrowStrange** [comment]
As it looks you set the environment variable in a wrong way. Is this a typo, or are you actually calling `export export`?

Here is the correct way if you want to run the script from the command line(example Token):
_Please replace the example token with your token._

```
export HETZNER_AUTH_API_TOKEN='925bf046408b55c313740eef2bc18b1e'
./dyndns.sh -Z example.com -n dyn -T AAAA
```

**Comment by MrTiptop** [comment]
Yeah it’s a typo sorry about that.

this is running on my qnap if that matters

**Comment by FarrowStrange** [comment]
Another option is to store the API token directly in the script. The corresponding option can be found in line 6 of the script:
```
...
auth_api_token=${HETZNER_AUTH_API_TOKEN:-'your-hetzner-dns-api-token'}
...
```

Then you don't need to export the API token as an environment variable and can just call the script like this:
```
./dyndns.sh -Z example.com -n dyn -T AAAA
```

**Comment by MrTiptop** [comment]
Hello i just tried again, and got the same error

`# ./dyndns.sh -Z example.com -n dyn
Error: Record_Name: dyn : Something went wrong. Could not find Zone ID.
Error: Record_Name: dyn : Check your inputs of either -z <Zone ID> or -Z <Zone Name>.
Error: Record_Name: dyn : Use -h to display help.
`

i added token in the script

`#!/bin/bash
`# DynDNS Script for Hetzner DNS API by FarrowStrange
`#` v1.1

`#` get OS environment variables
auth_api_token=${HETZNER_AUTH_API_TOKEN:-'AbCdsasfasfasfdasfas'}

zone_name=${HETZNER_ZONE_NAME:-''}
zone_id=${HETZNER_ZONE_ID:-''}

record_name=${HETZNER_RECORD_NAME:-''}
record_ttl=${HETZNER_RECORD_TTL:-'60'}
record_type=${HETZNER_RECORD_TYPE:-'A'}

display_help() {
  cat <<EOF
`
