### ISSUE TITLE
script cant find "Jq"

### ISSUE THREAD

**Issue by antonov124** [FarrowStrange/hetzner-api-dyndns#23]
script wont run, it says jq is not installed. But there it is ;(
`pi@raspberrypi:~/dns/hetzner-api-dyndns $ sh dyndns.sh
Error: Record_Name: XYZ : To run the script 'jq' is needed, but it seems not to be installed.
/usr/bin/jq
Error: Record_Name: XYZ : Please check 'https://github.com/FarrowStrange/hetzner-api-dyndns#install-jq' for more informations and try again.
`
----

`sudo apt-get install jq
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
jq ist schon die neueste Version (1.5+dfsg-2+b1).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 1 nicht aktualisiert.`

`pi@raspberrypi:/usr/bin $ jq
jq - commandline JSON processor [version 1.5-1-a5b5cbe]
Usage: jq [options] <jq filter> [file...]

        jq is a tool for processing JSON inputs, applying the
        given filter to its JSON text inputs and producing the
        filter's results as JSON on standard output.
        The simplest filter is ., which is the identity filter,
        copying jq's input to its output unmodified (except for
        formatting).
        For more advanced filters see the jq(1) manpage ("man jq")
        and/or https://stedolan.github.io/jq

        Some of the options include:
         -c             compact instead of pretty-printed output;
         -n             use `null` as the single input value;
         -e             set the exit status code based on the output;
         -s             read (slurp) all inputs into an array; apply filter to it;
         -r             output raw strings, not JSON texts;
         -R             read raw strings, not JSON texts;
         -C             colorize JSON;
         -M             monochrome (don't colorize JSON);
         -S             sort keys of objects on output;
         --tab  use tabs for indentation;
         --arg a v      set variable $a to value <v>;
         --argjson a v  set variable $a to JSON value <v>;
         --slurpfile a f        set variable $a to an array of JSON texts read from <f>;
        See the manpage for more options.
`
any ideas?

**Comment by FarrowStrange** [comment]
Hey @antonov124,

thank you for your message, I will try to help you 😄 

Can you tell me the output of following command?
```
$ command -v jq
```

**Comment by antonov124** [comment]
Hier bitte ;)
pi@raspberrypi:~ $ command -v jq
/usr/bin/jq

**Comment by FarrowStrange** [comment]
Hey @antonov124,
bitte entschuldige die späte Antwort.

Ich habe gerade ein paar Tests durchgeführt und wie es aussieht wird die Schleife zur Prüfung der installierten Tools durch die **sh (Bourne Shell)** anders interpretiert.
Kannst du bitte einmal prüfen das Script explizit mit der **Bash (Bourne-again shell)** aufzurufen?

```
$ /bin/bash /path/to/dyndns.sh
```

**Comment by antonov124** [comment]
Der Befehl hat geklappt.   Also so dann die die cron eintragen?
Oder passt du etwas in der "sh" an?
gruß

**Comment by FarrowStrange** [comment]
Ich notiere mir mal, dass ich beim nächsten mal eine Abfrage der Environment Shell in das Script einbaue.

Genau, am besten trägst du es z.B. so in die Crontab ein um sicher zu gehen das das Script im Environment mit der Bourne-again Shell ausgeführt wird:

```
HETZNER_AUTH_API_TOKEN='<your-hetzner-dns-api-token>'

*/5 * * * * /bin/bash /path/to/dyndns.sh -Z example.com -n dyn
```

Vielen Dank führ deine Hilfe und deine Geduld - dann würde ich das Issue hier schließen 🚀
