### ISSUE TITLE
Additional version as Python script

### ISSUE THREAD

**Issue by FarrowStrange** [FarrowStrange/hetzner-api-dyndns#7]
To improve my Python skills, I decided to write another version in Python. Stay tuned 😁

**Comment by ReinerNippes** [comment]
Don't know if it's helpful, but there is an Ansible module for Hetzner DNS in the making. 
https://git.osuv.de/m/hetzner_dns/src/branch/main/plugins/module_utils/helper.py
Maybe you can get some inspiration for your python script.
