### ISSUE TITLE
Script creates new A record

### ISSUE THREAD

**Issue by murmelbahn** [FarrowStrange/hetzner-api-dyndns#8]
Hi,

nice script dude. Sadly the script creates a new A record instead of updating the created one.
Can you fix this?

**Comment by murmelbahn** [comment]
Nevermind:>

**Comment by FarrowStrange** [comment]
Hey @murmelbahn,

Since you have already closed the problem again, I assume that you were able to fix it? If you want you can tell me where exactly the problem was. If necessary, I can adjust the documentation accordingly.

If you have any further questions, please feel free to contact me. 😁

**Comment by murmelbahn** [comment]
I dont know i think it was a fuckup at my configuration. I have tried to force the problem to appear but it did not happend so i gues its not an error. The documentation is easy understandable nothing to change from my point of view.

**Comment by FarrowStrange** [comment]
Thanks for your feedback - I hope now everything works without problems.
Feel free to propose further changes or open issues, if there are any.
